##################################################################
# Dockerfile para la configuracion de Misura con NodeJS - Express
##################################################################
# Imagen Base
FROM alpine:3.1

ENV PORT=4000
# User
# USER node

# Metadata
LABEL "cl.jacm.bpnodets"="jacm"
LABEL maintainer="jacanepa@gmail.com"
LABEL author="Juan A Canepa"
LABEL version="1.0"

# Install dependencies
RUN npm i babel-cli -g && \
    npm i pm2 -g

# Create app directory
# RUN mkdir -p /opt/misurabackend

# Select working directory
WORKDIR /opt/misurabackend
# Copy files to working directory
ADD . /opt/misurabackend

RUN npm install && \
    npm run-script build

# Copy tarball
RUN cp /opt/misurabackend/dist/misuraBackend.tar.gz /home && echo "Tarball Copiado!"
WORKDIR /home
RUN tar xvfz misuraBackend.tar.gz && echo "Descomprimido el Tarball de /home"

WORKDIR /home/misuraBackend

EXPOSE 4000

# UP PM2
CMD [ "pm2-runtime", "src/app/index.js" ]
# CMD ["pm2", "start","index.js"]
#CMD ["node","src/app/index.js"]