########################################################################################
# Dockerfile para la configuracion de bpnodets - NodeJS - TypeScript - Express - TypeORM 
########################################################################################
# Imagen Base
FROM mhart/alpine-node:12
ENV NODE_ENV=test

# Install dependencies
RUN npm update && \
    npm i yarn -g  && \
    npm i mocha -g && \
    npm i chai -g && \
    npm i typescript -g \
    npm i ts-node -g

WORKDIR /home/bpnodets

# Copy files to working directory
ADD . /home/bpnodets

RUN yarn 
RUN env
# Create environment file
# RUN cp .env.test .env

CMD ["mocha", "-r", "ts-node/register", "src/tests/*.test.ts"]